name: CI/CD for Nest.js Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  Build:
    runs-on: ubuntu-latest
    needs: [Clone-down]
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: 
          - npm install
          - npm install deepai

      - name: Build Application
        run: npm run build
  Dockerize backend:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Set up Docker
        uses: docker/setup-action@v2

      - name: Build and Push Docker Image
      #modify docker image name
      - name: build gcr images
        run: chmod +x build_push_gcr.sh && build_push_gcr.sh

  
  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: [Dockerize]
  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2

  #   - name: Set up kubectl
  #     uses: docker://louislam/autopilot:latest
  #     with:
  #       args: install kubectl

  #   - name: Deploy to Kubernetes
  #     run: kubectl --kubeconfig ${{ secrets.KUBECONFIG }} apply -f kubernetes
