apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: backend
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
        - image: gcr.io/cloud-handin-project/backend-img:latest
          name: google-cloud-platform-app
          ports:
            - containerPort: 9000