version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"  # Expose the necessary ports if needed
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: cloudDB
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge